export const subCategories = [
    {
    parentCourse: 'Development',
    courseId: 'web-2023',
    name: 'Web Development',
    courseImage: "",
    previewVideoThumbnail: 'https: //cdn.videvo.net/videvo_files/video/free/2022-11/thumbnails/221017_01_Urban%20Football_4k_044_small.jpg',
    previewVideo: 'https: //joy1.videvo.net/videvo_files/video/free/video0474/large_watermarked/_import_61ea3dd6ab62a0.19123787_preview.mp4',
    title: "Some preview title",
    desc: 'Some preview Description',
    lectures: [
            {
        id: 1,
        thumbail: "",
        video: 'https: //joy1.videvo.net/videvo_files/video/free/video0474/large_watermarked/_import_61ea3dd6ab62a0.19123787_preview.mp4',
        title: 'Introduction to HTML.',
        desc: 'HTML is markup langugage use to build web page structure',
        isWatched: false,
        readMore: 'Read more',
            },
            {
        id: 2,
        thumbail: "",
        video: 'https: //joy1.videvo.net/videvo_files/video/free/video0465/large_watermarked/_import_612e195368c859.79999247_preview.mp4',
        title: 'Introduction to CSS.',
        desc: 'CSS is Cascading style sheet langugage use to make up the web page structure',
        isWatched: false,
        readMore: 'Read more',
            },
        ],
    isCompleted: false,
    completedDate: null
    },
    {
    parentCourse: 'Development',
    courseId: 'app-2023',
    name: 'App Development',
    courseImage: "",
    previewVideoThumbnail: 'https: //cdn.videvo.net/videvo_files/video/free/2022-11/thumbnails/221017_01_Urban%20Football_4k_044_small.jpg',
    previewVideo: 'https: //joy1.videvo.net/videvo_files/video/free/video0474/large_watermarked/_import_61ea3dd6ab62a0.19123787_preview.mp4',
    title: "Some preview title",
    desc: 'Aquick Brown Fox jumps over the lazy dog.',
    lectures: [
            {
        id: 1,
        thumbail: "",
        video: 'https: //joy1.videvo.net/videvo_files/video/free/video0474/large_watermarked/_import_61ea3dd6ab62a0.19123787_preview.mp4',
        title: 'Introduction To React Native.',
        desc: 'React Native is pupular and demanded langugage use to build IOS and Android application',
        isWatched: false,
        readMore: 'Read more',
            },
            {
        id: 2,
        thumbail: "",
        video: 'https: //joy1.videvo.net/videvo_files/video/free/video0465/large_watermarked/_import_612e195368c859.79999247_preview.mp4',
        title: 'Introduction to State and props.',
        desc: 'React Native is Cascading style sheet langugage use to make up the web page structure',
        isWatched: false,
        readMore: 'Read more',
            },
        ],
    isCompleted: false,
    completedDate: null
    },
    {
    parentCourse: 'Development',
    courseId: 'Fitnes-2023',
    name: 'Fitness Course',
    courseImage: "",
    previewVideoThumbnail: 'https: //cdn.videvo.net/videvo_files/video/free/2022-11/thumbnails/221017_01_Urban%20Football_4k_044_small.jpg',
    previewVideo: 'https: //joy1.videvo.net/videvo_files/video/free/video0474/large_watermarked/_import_61ea3dd6ab62a0.19123787_preview.mp4',
    title: "Some preview title",

    desc: 'Aquick Brown Fox jumps over the lazy dog.',
    lectures: [
            {
        id: 1,
        thumbail: "",
        video: 'https: //joy1.videvo.net/videvo_files/video/free/video0474/large_watermarked/_import_61ea3dd6ab62a0.19123787_preview.mp4',
        title: 'Introduction To React Native.',
        desc: 'React Native is pupular and demanded langugage use to build IOS and Android application',
        isWatched: false,
        readMore: 'Read more',
            },
            {
        id: 2,
        thumbail: "",
        video: 'https: //joy1.videvo.net/videvo_files/video/free/video0465/large_watermarked/_import_612e195368c859.79999247_preview.mp4',
        title: 'Introduction to State and props.',
        desc: 'React Native is Cascading style sheet langugage use to make up the web page structure',
        isWatched: false,
        readMore: 'Read more',
            },
        ],
    isCompleted: false,
    completedDate: null
    },
    {
    parentCourse: 'Business',
    courseId: 'budget-and-forecast-2023',
    name: 'How to Budget and Forecast for Your Businessby',
    courseImage: "",
    previewVideoThumbnail: 'https: //cdn.videvo.net/videvo_files/video/free/2022-11/thumbnails/221017_01_Urban%20Football_4k_044_small.jpg',
    previewVideo: 'https: //joy1.videvo.net/videvo_files/video/free/video0474/large_watermarked/_import_61ea3dd6ab62a0.19123787_preview.mp4',
    title: "Some preview title",
    desc: 'Aquick Brown Fox jumps over the lazy dog.',
    lectures: [
            {
        id: 1,
        thumbail: "",
        video: 'https: //joy1.videvo.net/videvo_files/video/free/video0474/large_watermarked/_import_61ea3dd6ab62a0.19123787_preview.mp4',
        title: 'Introduction to HTML.',
        desc: 'HTML is markup langugage use to build web page structure',
        isWatched: false,
        readMore: 'Read more',
            },
            {
        id: 2,
        thumbail: "",
        video: 'https: //joy1.videvo.net/videvo_files/video/free/video0465/large_watermarked/_import_612e195368c859.79999247_preview.mp4',
        title: 'Introduction to CSS.',
        desc: 'CSS is Cascading style sheet langugage use to make up the web page structure',
        isWatched: false,
        readMore: 'Read more',
            },
        ],
    isCompleted: false,
    completedDate: null
    },
    {
    parentCourse: 'Business',
    courseId: 'bussines-writing-2023',
    name: 'Powerful business writing: How to write concisely',
    courseImage: "",
    previewVideoThumbnail: 'https: //cdn.videvo.net/videvo_files/video/free/2022-11/thumbnails/221017_01_Urban%20Football_4k_044_small.jpg',
    previewVideo: 'https: //joy1.videvo.net/videvo_files/video/free/video0474/large_watermarked/_import_61ea3dd6ab62a0.19123787_preview.mp4',
    title: "Some preview title",
    desc: 'Aquick Brown Fox jumps over the lazy dog.',
    lectures: [
            {
        id: 1,
        thumbail: "",
        video: 'https: //joy1.videvo.net/videvo_files/video/free/video0474/large_watermarked/_import_61ea3dd6ab62a0.19123787_preview.mp4',
        title: 'Introduction To React Native.',
        desc: 'React Native is pupular and demanded langugage use to build IOS and Android application',
        isWatched: false,
        readMore: 'Read more',
            },
            {
        id: 2,
        thumbail: "",
        video: 'https: //joy1.videvo.net/videvo_files/video/free/video0465/large_watermarked/_import_612e195368c859.79999247_preview.mp4',
        title: 'Introduction to State and props.',
        desc: 'React Native is Cascading style sheet langugage use to make up the web page structure',
        isWatched: false,
        readMore: 'Read more',
            },
        ],
    isCompleted: false,
    completedDate: null
    },
    {
    parentCourse: 'Business',
    courseId: 'leadership-program-2023',
    name: 'Chief Financial Officer Leadership Program',
    courseImage: "",
    previewVideoThumbnail: 'https: //cdn.videvo.net/videvo_files/video/free/2022-11/thumbnails/221017_01_Urban%20Football_4k_044_small.jpg',
    previewVideo: 'https: //joy1.videvo.net/videvo_files/video/free/video0474/large_watermarked/_import_61ea3dd6ab62a0.19123787_preview.mp4',
    title: "Some preview title",
    desc: 'Aquick Brown Fox jumps over the lazy dog.',
    lectures: [
            {
        id: 1,
        thumbail: "",
        video: 'https: //joy1.videvo.net/videvo_files/video/free/video0474/large_watermarked/_import_61ea3dd6ab62a0.19123787_preview.mp4',
        title: 'Introduction To React Native.',
        desc: 'React Native is pupular and demanded langugage use to build IOS and Android application',
        isWatched: false,
        readMore: 'Read more',
            },
            {
        id: 2,
        thumbail: "",
        video: 'https: //joy1.videvo.net/videvo_files/video/free/video0465/large_watermarked/_import_612e195368c859.79999247_preview.mp4',
        title: 'Introduction to State and props.',
        desc: 'React Native is Cascading style sheet langugage use to make up the web page structure',
        isWatched: false,
        readMore: 'Read more',
            },
        ],
    isCompleted: false,
    completedDate: null
    }
]